language: node_js
node_js:
- '0.10'
before_install:
- sudo apt-get install expect
- curl https://install.meteor.com | /bin/sh
branches:
  only:
  - master
env:
  global:
  - METEOR_DEPLOY_URL=notifications-example.meteor.com
  - secure: kBivFIGXouT6x5KxNMLi58zlvZ8ykx+B0CEVKU9GniojjK7CKJzx4sVIujiN2K1W+PYssXBvlaf8K/fj6Am0vTpkgFVE0Eum0POBkeDpix5cF7ZgdQYvruXeLt/hHbziD9JXS82pwr8b6csbw4V/xhJwP5rkIdhlXgwLiDbaWhI=
  - secure: bPKIVBzRFyCKq8Rng6ePlRslS72hjzYcquK0jB/skk7wR1SjqdbidT5W5QMwDQZTOUErCMdBA81Ulc7RjckFvUe625t/avjOyvnkEM0oh1JJoPrSavJ5kUCa4lfomar1K0Yc1FRkvUBfaPFmpKVeyjvp0rdPbR2nY69ny3wB9zw=
  - secure: Tba8hTTss89bs3q1knRnzOsOBn1EpQM5GsSz1U4EkaE14t0psAMgISyaCaNtRqJi2cEb3dtPlDNMoSuzd84nmigIeEeileXYHr65SNXolcTWQSKhOCNXP9rU5gYlgwhIOkIy7CDyFotr9Eq40K9Bmye4rLSCUEcmpB0RnGpTHvo=
  - secure: UO9O60roq3HrQ8hFzy9xbhefoQPHgCveGQmq+Z7090zDWUvn3rHt56PT3k+9nQiRZzs4cSZKuTpe8uFTtMkG4VveyxL/KIxAviskVAME/u+9IRbUG802ffdk9Rt3AyVc6GibuBROoFWUJqrncQOwwB1YSf6a8UtnzHWgtTFfHQE=
script: "./run_nightwatch.sh"
