language: node_js
node_js:
- '0.10'
before_install:
- sudo apt-get install expect
- curl https://install.meteor.com | /bin/sh
- meteor update
- npm install
branches:
  only:
  - master
env:
  global:
  - METEOR_DEPLOY_URL=notifications-example.meteor.com
  - secure: f8npqN7Pcf4E8MIhqJEpk5RZG3sGoXIeLTJS8DuKGwad1Zuf2I99WpaTZRHZHnOW76MbppT5C4XYfy3F44PTCMexey35BkS9mXy+/ZoWhiJUUtcDqqoT8Prlnx5FgH3idhBfXz4mCyNH/FIDRbSLOhviOB4WGTsTesvp0uMlsJI=
  - secure: qoMcH/wRdlCfMogIxQwwIa2NVg4KHgH5s6tCrbIkg7yzcygxZ0E9s1DVAjYDKp3wkV021zjrQA1MODICFeMrUoE1PWwPiPKhUTj50o8uqF8DyEvlhFo/LrC+2avRmXxtuvNKue71eOrbScchcQdHniDKhfSV15EcKaTJAXEQqnE=
  - secure: XFnTkyVQKfMR/nzQLJw7xr795UlQ/hBAO5GZXkufv1DXcNGI8T8j4Fa9u6TEfxkgD4B4S72tfLgG1ku7OfmMgI174k2ukLc4fVIHCYXVm52dQ7c8el+TwZMBa+RsNWEjDr+GAMljCJP4Wp9a71FSk5exA3LAhjSG8m56LgnPGzA=
  - secure: hOmJobNW7oafw2kV1AtO//4HDlLRThDjV6gIqMvtGY0+hT+ZTb4ZhAULrCg+CkodGzKNy5nVfStn0dGZurGFwS9VKDybZVpb7ECsYmH0WuvZwUJ8fhJLcWKFTTV2aXWwdNTFWXaKydllLbr0gYSYLN+oSkFFbxTjGPL0rh363Hs=
script:
- expect deploy.exp
- sleep 5
- "./run_nightwatch.sh -e browserstack"
notifications:
  slack:
    secure: YRKmcH7O9ANB8i7K1mMSh0BvDhmlnWMH5i1mg32fb7WOjdo28C+qO0366KugcM3IrTkEUmFSatDOwJWpU98VIjuLLhziRFc5b7k65nZRpGZRsnLESVGRS3AAtJlQD7ZZIc0z0O6GAhTqB29hLs3trxpO1R8maxFPh9lEoKtwP04=
